### ISSUE TITLE
New command line argument to identify working directory for temporary files

### ISSUE THREAD

**Issue by newhoggy** [arbor/topictap#5]

**Comment by AlexeyRaga** [comment]
Can't it be system `temp` directory?

**Comment by AlexeyRaga** [comment]
Or maybe make it optional in case if we want to override

**Comment by newhoggy** [comment]
It should be configurable in case we need to put it in a mounted folder.

**Comment by newhoggy** [comment]
We decided a long time ago that optional configuration is harmful because they are easily forgotten.
